FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies.
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get update -y \
    && apt-get install -y nodejs

RUN mkdir -p /code

WORKDIR /code

COPY requirements.txt /tmp/requirements.txt

RUN pip install uv
RUN uv venv
RUN uv pip install -r /tmp/requirements.txt

COPY . /code

RUN .venv/bin/python manage.py collectstatic --noinput

EXPOSE 8000

CMD [".venv/bin/granian", "--host", "0.0.0.0", "--port", "8080", "--http2-keep-alive-timeout", "300", "--interface", "wsgi", "{{project_name}}.wsgi:application"]
