# Generated by Django 5.1.1 on 2025-03-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("change", models.DecimalField(decimal_places=2, max_digits=10)),
                ("percent_change", models.DecimalField(decimal_places=2, max_digits=5)),
                ("volume", models.BigIntegerField()),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stock_ticker",
                "ordering": ["-date", "symbol"],
            },
        ),
    ]
